// Universal stock list — generated from official NSE index constituents.
// Sources: NSE indices (Nifty 50, Nifty Next 50, Nifty Midcap 150,
// Nifty Smallcap 250, Nifty Microcap 250). Each stock is tagged with the
// highest-cap index it belongs to. Yahoo Finance symbols use the ".NS" suffix.
export type IndexName =
  | "Nifty 50"
  | "Nifty Next 50"
  | "Nifty Midcap 150"
  | "Nifty Smallcap 250"
  | "Nifty Microcap 250";

export const INDICES: IndexName[] = [
  "Nifty 50",
  "Nifty Next 50",
  "Nifty Midcap 150",
  "Nifty Smallcap 250",
  "Nifty Microcap 250",
];

export interface UniverseStock {
  symbol: string; // Yahoo symbol
  name: string;
  sector: string;
  index: IndexName;
}

export const UNIVERSE: UniverseStock[] = [
  { symbol: "ADANIENT.NS", name: "Adani Enterprises", sector: "Metals & Mining", index: "Nifty 50" },
  { symbol: "ADANIPORTS.NS", name: "Adani Ports and Special Economic Zone", sector: "Services", index: "Nifty 50" },
  { symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals Enterprise", sector: "Healthcare", index: "Nifty 50" },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints", sector: "Consumer Durables", index: "Nifty 50" },
  { symbol: "AXISBANK.NS", name: "Axis Bank", sector: "Financial Services", index: "Nifty 50" },
  { symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto", sector: "Automobile and Auto Components", index: "Nifty 50" },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance", sector: "Financial Services", index: "Nifty 50" },
  { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv", sector: "Financial Services", index: "Nifty 50" },
  { symbol: "BEL.NS", name: "Bharat Electronics", sector: "Capital Goods", index: "Nifty 50" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel", sector: "Telecommunication", index: "Nifty 50" },
  { symbol: "CIPLA.NS", name: "Cipla", sector: "Healthcare", index: "Nifty 50" },
  { symbol: "COALINDIA.NS", name: "Coal India", sector: "Oil Gas & Consumable Fuels", index: "Nifty 50" },
  { symbol: "DRREDDY.NS", name: "Dr. Reddy's Laboratories", sector: "Healthcare", index: "Nifty 50" },
  { symbol: "EICHERMOT.NS", name: "Eicher Motors", sector: "Automobile and Auto Components", index: "Nifty 50" },
  { symbol: "ETERNAL.NS", name: "Eternal", sector: "Consumer Services", index: "Nifty 50" },
  { symbol: "GRASIM.NS", name: "Grasim Industries", sector: "Construction Materials", index: "Nifty 50" },
  { symbol: "HCLTECH.NS", name: "HCL Technologies", sector: "Information Technology", index: "Nifty 50" },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank", sector: "Financial Services", index: "Nifty 50" },
  { symbol: "HDFCLIFE.NS", name: "HDFC Life Insurance Company", sector: "Financial Services", index: "Nifty 50" },
  { symbol: "HINDALCO.NS", name: "Hindalco Industries", sector: "Metals & Mining", index: "Nifty 50" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever", sector: "Fast Moving Consumer Goods", index: "Nifty 50" },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank", sector: "Financial Services", index: "Nifty 50" },
  { symbol: "ITC.NS", name: "ITC", sector: "Fast Moving Consumer Goods", index: "Nifty 50" },
  { symbol: "INFY.NS", name: "Infosys", sector: "Information Technology", index: "Nifty 50" },
  { symbol: "INDIGO.NS", name: "InterGlobe Aviation", sector: "Services", index: "Nifty 50" },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel", sector: "Metals & Mining", index: "Nifty 50" },
  { symbol: "JIOFIN.NS", name: "Jio Financial Services", sector: "Financial Services", index: "Nifty 50" },
  { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank", sector: "Financial Services", index: "Nifty 50" },
  { symbol: "LT.NS", name: "Larsen & Toubro", sector: "Construction", index: "Nifty 50" },
  { symbol: "M&M.NS", name: "Mahindra & Mahindra", sector: "Automobile and Auto Components", index: "Nifty 50" },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki India", sector: "Automobile and Auto Components", index: "Nifty 50" },
  { symbol: "MAXHEALTH.NS", name: "Max Healthcare Institute", sector: "Healthcare", index: "Nifty 50" },
  { symbol: "NTPC.NS", name: "NTPC", sector: "Power", index: "Nifty 50" },
  { symbol: "NESTLEIND.NS", name: "Nestle India", sector: "Fast Moving Consumer Goods", index: "Nifty 50" },
  { symbol: "ONGC.NS", name: "Oil & Natural Gas Corporation", sector: "Oil Gas & Consumable Fuels", index: "Nifty 50" },
  { symbol: "POWERGRID.NS", name: "Power Grid Corporation of India", sector: "Power", index: "Nifty 50" },
  { symbol: "RELIANCE.NS", name: "Reliance Industries", sector: "Oil Gas & Consumable Fuels", index: "Nifty 50" },
  { symbol: "SBILIFE.NS", name: "SBI Life Insurance Company", sector: "Financial Services", index: "Nifty 50" },
  { symbol: "SHRIRAMFIN.NS", name: "Shriram Finance", sector: "Financial Services", index: "Nifty 50" },
  { symbol: "SBIN.NS", name: "State Bank of India", sector: "Financial Services", index: "Nifty 50" },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharmaceutical Industries", sector: "Healthcare", index: "Nifty 50" },
  { symbol: "TCS.NS", name: "Tata Consultancy Services", sector: "Information Technology", index: "Nifty 50" },
  { symbol: "TATACONSUM.NS", name: "Tata Consumer Products", sector: "Fast Moving Consumer Goods", index: "Nifty 50" },
  { symbol: "TMPV.NS", name: "Tata Motors Passenger Vehicles", sector: "Automobile and Auto Components", index: "Nifty 50" },
  { symbol: "TATASTEEL.NS", name: "Tata Steel", sector: "Metals & Mining", index: "Nifty 50" },
  { symbol: "TECHM.NS", name: "Tech Mahindra", sector: "Information Technology", index: "Nifty 50" },
  { symbol: "TITAN.NS", name: "Titan Company", sector: "Consumer Durables", index: "Nifty 50" },
  { symbol: "TRENT.NS", name: "Trent", sector: "Consumer Services", index: "Nifty 50" },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement", sector: "Construction Materials", index: "Nifty 50" },
  { symbol: "WIPRO.NS", name: "Wipro", sector: "Information Technology", index: "Nifty 50" },
  { symbol: "ABB.NS", name: "ABB India", sector: "Capital Goods", index: "Nifty Next 50" },
  { symbol: "ADANIENSOL.NS", name: "Adani Energy Solutions", sector: "Power", index: "Nifty Next 50" },
  { symbol: "ADANIGREEN.NS", name: "Adani Green Energy", sector: "Power", index: "Nifty Next 50" },
  { symbol: "ADANIPOWER.NS", name: "Adani Power", sector: "Power", index: "Nifty Next 50" },
  { symbol: "AMBUJACEM.NS", name: "Ambuja Cements", sector: "Construction Materials", index: "Nifty Next 50" },
  { symbol: "DMART.NS", name: "Avenue Supermarts", sector: "Consumer Services", index: "Nifty Next 50" },
  { symbol: "BAJAJHLDNG.NS", name: "Bajaj Holdings & Investment", sector: "Financial Services", index: "Nifty Next 50" },
  { symbol: "BANKBARODA.NS", name: "Bank of Baroda", sector: "Financial Services", index: "Nifty Next 50" },
  { symbol: "BPCL.NS", name: "Bharat Petroleum Corporation", sector: "Oil Gas & Consumable Fuels", index: "Nifty Next 50" },
  { symbol: "BOSCHLTD.NS", name: "Bosch", sector: "Automobile and Auto Components", index: "Nifty Next 50" },
  { symbol: "BRITANNIA.NS", name: "Britannia Industries", sector: "Fast Moving Consumer Goods", index: "Nifty Next 50" },
  { symbol: "CGPOWER.NS", name: "CG Power and Industrial Solutions", sector: "Capital Goods", index: "Nifty Next 50" },
  { symbol: "CANBK.NS", name: "Canara Bank", sector: "Financial Services", index: "Nifty Next 50" },
  { symbol: "CHOLAFIN.NS", name: "Cholamandalam Investment and Finance Company", sector: "Financial Services", index: "Nifty Next 50" },
  { symbol: "CUMMINSIND.NS", name: "Cummins India", sector: "Capital Goods", index: "Nifty Next 50" },
  { symbol: "DLF.NS", name: "DLF", sector: "Realty", index: "Nifty Next 50" },
  { symbol: "DIVISLAB.NS", name: "Divi's Laboratories", sector: "Healthcare", index: "Nifty Next 50" },
  { symbol: "GAIL.NS", name: "GAIL (India)", sector: "Oil Gas & Consumable Fuels", index: "Nifty Next 50" },
  { symbol: "GODREJCP.NS", name: "Godrej Consumer Products", sector: "Fast Moving Consumer Goods", index: "Nifty Next 50" },
  { symbol: "HDFCAMC.NS", name: "HDFC Asset Management Company", sector: "Financial Services", index: "Nifty Next 50" },
  { symbol: "HAL.NS", name: "Hindustan Aeronautics", sector: "Capital Goods", index: "Nifty Next 50" },
  { symbol: "HINDZINC.NS", name: "Hindustan Zinc", sector: "Metals & Mining", index: "Nifty Next 50" },
  { symbol: "HYUNDAI.NS", name: "Hyundai Motor India", sector: "Automobile and Auto Components", index: "Nifty Next 50" },
  { symbol: "INDHOTEL.NS", name: "Indian Hotels Co.", sector: "Consumer Services", index: "Nifty Next 50" },
  { symbol: "IOC.NS", name: "Indian Oil Corporation", sector: "Oil Gas & Consumable Fuels", index: "Nifty Next 50" },
  { symbol: "IRFC.NS", name: "Indian Railway Finance Corporation", sector: "Financial Services", index: "Nifty Next 50" },
  { symbol: "JINDALSTEL.NS", name: "Jindal Steel", sector: "Metals & Mining", index: "Nifty Next 50" },
  { symbol: "LTM.NS", name: "LTM", sector: "Information Technology", index: "Nifty Next 50" },
  { symbol: "LODHA.NS", name: "Lodha Developers", sector: "Realty", index: "Nifty Next 50" },
  { symbol: "MAZDOCK.NS", name: "Mazagoan Dock Shipbuilders", sector: "Capital Goods", index: "Nifty Next 50" },
  { symbol: "MUTHOOTFIN.NS", name: "Muthoot Finance", sector: "Financial Services", index: "Nifty Next 50" },
  { symbol: "PIDILITIND.NS", name: "Pidilite Industries", sector: "Chemicals", index: "Nifty Next 50" },
  { symbol: "PFC.NS", name: "Power Finance Corporation", sector: "Financial Services", index: "Nifty Next 50" },
  { symbol: "PNB.NS", name: "Punjab National Bank", sector: "Financial Services", index: "Nifty Next 50" },
  { symbol: "RECLTD.NS", name: "REC", sector: "Financial Services", index: "Nifty Next 50" },
  { symbol: "MOTHERSON.NS", name: "Samvardhana Motherson International", sector: "Automobile and Auto Components", index: "Nifty Next 50" },
  { symbol: "SHREECEM.NS", name: "Shree Cement", sector: "Construction Materials", index: "Nifty Next 50" },
  { symbol: "ENRIN.NS", name: "Siemens Energy India", sector: "Capital Goods", index: "Nifty Next 50" },
  { symbol: "SIEMENS.NS", name: "Siemens", sector: "Capital Goods", index: "Nifty Next 50" },
  { symbol: "SOLARINDS.NS", name: "Solar Industries India", sector: "Chemicals", index: "Nifty Next 50" },
  { symbol: "TVSMOTOR.NS", name: "TVS Motor Company", sector: "Automobile and Auto Components", index: "Nifty Next 50" },
  { symbol: "TATACAP.NS", name: "Tata Capital", sector: "Financial Services", index: "Nifty Next 50" },
  { symbol: "TMCV.NS", name: "Tata Motors", sector: "Capital Goods", index: "Nifty Next 50" },
  { symbol: "TATAPOWER.NS", name: "Tata Power Co.", sector: "Power", index: "Nifty Next 50" },
  { symbol: "TORNTPHARM.NS", name: "Torrent Pharmaceuticals", sector: "Healthcare", index: "Nifty Next 50" },
  { symbol: "UNIONBANK.NS", name: "Union Bank of India", sector: "Financial Services", index: "Nifty Next 50" },
  { symbol: "UNITDSPR.NS", name: "United Spirits", sector: "Fast Moving Consumer Goods", index: "Nifty Next 50" },
  { symbol: "VBL.NS", name: "Varun Beverages", sector: "Fast Moving Consumer Goods", index: "Nifty Next 50" },
  { symbol: "VEDL.NS", name: "Vedanta", sector: "Metals & Mining", index: "Nifty Next 50" },
  { symbol: "ZYDUSLIFE.NS", name: "Zydus Lifesciences", sector: "Healthcare", index: "Nifty Next 50" },
  { symbol: "360ONE.NS", name: "360 ONE WAM", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "3MINDIA.NS", name: "3M India", sector: "Diversified", index: "Nifty Midcap 150" },
  { symbol: "ACC.NS", name: "ACC", sector: "Construction Materials", index: "Nifty Midcap 150" },
  { symbol: "AIAENG.NS", name: "AIA Engineering", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "APLAPOLLO.NS", name: "APL Apollo Tubes", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "AUBANK.NS", name: "AU Small Finance Bank", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "AWL.NS", name: "AWL Agri Business", sector: "Fast Moving Consumer Goods", index: "Nifty Midcap 150" },
  { symbol: "ABBOTINDIA.NS", name: "Abbott India", sector: "Healthcare", index: "Nifty Midcap 150" },
  { symbol: "ATGL.NS", name: "Adani Total Gas", sector: "Oil Gas & Consumable Fuels", index: "Nifty Midcap 150" },
  { symbol: "ABCAPITAL.NS", name: "Aditya Birla Capital", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "AJANTPHARM.NS", name: "Ajanta Pharmaceuticals", sector: "Healthcare", index: "Nifty Midcap 150" },
  { symbol: "ALKEM.NS", name: "Alkem Laboratories", sector: "Healthcare", index: "Nifty Midcap 150" },
  { symbol: "ANTHEM.NS", name: "Anthem Biosciences", sector: "Healthcare", index: "Nifty Midcap 150" },
  { symbol: "APARINDS.NS", name: "Apar Industries", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "APOLLOTYRE.NS", name: "Apollo Tyres", sector: "Automobile and Auto Components", index: "Nifty Midcap 150" },
  { symbol: "ASHOKLEY.NS", name: "Ashok Leyland", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "ASTRAL.NS", name: "Astral", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "AUROPHARMA.NS", name: "Aurobindo Pharma", sector: "Healthcare", index: "Nifty Midcap 150" },
  { symbol: "AIIL.NS", name: "Authum Investment & Infrastructure", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "BSE.NS", name: "BSE", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "BAJAJHFL.NS", name: "Bajaj Housing Finance", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "BALKRISIND.NS", name: "Balkrishna Industries", sector: "Automobile and Auto Components", index: "Nifty Midcap 150" },
  { symbol: "BANKINDIA.NS", name: "Bank of India", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "MAHABANK.NS", name: "Bank of Maharashtra", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "BERGEPAINT.NS", name: "Berger Paints India", sector: "Consumer Durables", index: "Nifty Midcap 150" },
  { symbol: "BDL.NS", name: "Bharat Dynamics", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "BHARATFORG.NS", name: "Bharat Forge", sector: "Automobile and Auto Components", index: "Nifty Midcap 150" },
  { symbol: "BHEL.NS", name: "Bharat Heavy Electricals", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "BHARTIHEXA.NS", name: "Bharti Hexacom", sector: "Telecommunication", index: "Nifty Midcap 150" },
  { symbol: "GROWW.NS", name: "Billionbrains Garage Ventures", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "BIOCON.NS", name: "Biocon", sector: "Healthcare", index: "Nifty Midcap 150" },
  { symbol: "BLUESTARCO.NS", name: "Blue Star", sector: "Consumer Durables", index: "Nifty Midcap 150" },
  { symbol: "CRISIL.NS", name: "CRISIL", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "COCHINSHIP.NS", name: "Cochin Shipyard", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "COFORGE.NS", name: "Coforge", sector: "Information Technology", index: "Nifty Midcap 150" },
  { symbol: "COLPAL.NS", name: "Colgate Palmolive (India)", sector: "Fast Moving Consumer Goods", index: "Nifty Midcap 150" },
  { symbol: "CONCOR.NS", name: "Container Corporation of India", sector: "Services", index: "Nifty Midcap 150" },
  { symbol: "COROMANDEL.NS", name: "Coromandel International", sector: "Chemicals", index: "Nifty Midcap 150" },
  { symbol: "DABUR.NS", name: "Dabur India", sector: "Fast Moving Consumer Goods", index: "Nifty Midcap 150" },
  { symbol: "DALBHARAT.NS", name: "Dalmia Bharat", sector: "Construction Materials", index: "Nifty Midcap 150" },
  { symbol: "DIXON.NS", name: "Dixon Technologies (India)", sector: "Consumer Durables", index: "Nifty Midcap 150" },
  { symbol: "ENDURANCE.NS", name: "Endurance Technologies", sector: "Automobile and Auto Components", index: "Nifty Midcap 150" },
  { symbol: "ESCORTS.NS", name: "Escorts Kubota", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "EXIDEIND.NS", name: "Exide Industries", sector: "Automobile and Auto Components", index: "Nifty Midcap 150" },
  { symbol: "NYKAA.NS", name: "FSN E-Commerce Ventures", sector: "Consumer Services", index: "Nifty Midcap 150" },
  { symbol: "FEDERALBNK.NS", name: "Federal Bank", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "FORTIS.NS", name: "Fortis Healthcare", sector: "Healthcare", index: "Nifty Midcap 150" },
  { symbol: "GVT&D.NS", name: "GE Vernova T&D India", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "GMRAIRPORT.NS", name: "GMR Airports", sector: "Services", index: "Nifty Midcap 150" },
  { symbol: "GICRE.NS", name: "General Insurance Corporation of India", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "GLAXO.NS", name: "Glaxosmithkline Pharmaceuticals", sector: "Healthcare", index: "Nifty Midcap 150" },
  { symbol: "GLENMARK.NS", name: "Glenmark Pharmaceuticals", sector: "Healthcare", index: "Nifty Midcap 150" },
  { symbol: "MEDANTA.NS", name: "Global Health", sector: "Healthcare", index: "Nifty Midcap 150" },
  { symbol: "GODFRYPHLP.NS", name: "Godfrey Phillips India", sector: "Fast Moving Consumer Goods", index: "Nifty Midcap 150" },
  { symbol: "GODREJIND.NS", name: "Godrej Industries", sector: "Diversified", index: "Nifty Midcap 150" },
  { symbol: "GODREJPROP.NS", name: "Godrej Properties", sector: "Realty", index: "Nifty Midcap 150" },
  { symbol: "FLUOROCHEM.NS", name: "Gujarat Fluorochemicals", sector: "Chemicals", index: "Nifty Midcap 150" },
  { symbol: "HDBFS.NS", name: "HDB Financial Services", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "HAVELLS.NS", name: "Havells India", sector: "Consumer Durables", index: "Nifty Midcap 150" },
  { symbol: "HEROMOTOCO.NS", name: "Hero MotoCorp", sector: "Automobile and Auto Components", index: "Nifty Midcap 150" },
  { symbol: "HEXT.NS", name: "Hexaware Technologies", sector: "Information Technology", index: "Nifty Midcap 150" },
  { symbol: "HINDPETRO.NS", name: "Hindustan Petroleum Corporation", sector: "Oil Gas & Consumable Fuels", index: "Nifty Midcap 150" },
  { symbol: "POWERINDIA.NS", name: "Hitachi Energy India", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "HONAUT.NS", name: "Honeywell Automation India", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "HUDCO.NS", name: "Housing & Urban Development Corporation", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "ICICIGI.NS", name: "ICICI Lombard General Insurance Company", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "ICICIAMC.NS", name: "ICICI Prudential Asset Management Company", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "ICICIPRULI.NS", name: "ICICI Prudential Life Insurance Company", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "IDFCFIRSTB.NS", name: "IDFC First Bank", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "ITCHOTELS.NS", name: "ITC Hotels", sector: "Consumer Services", index: "Nifty Midcap 150" },
  { symbol: "INDIANB.NS", name: "Indian Bank", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "IRCTC.NS", name: "Indian Railway Catering And Tourism Corporation", sector: "Consumer Services", index: "Nifty Midcap 150" },
  { symbol: "IREDA.NS", name: "Indian Renewable Energy Development Agency", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "INDUSTOWER.NS", name: "Indus Towers", sector: "Telecommunication", index: "Nifty Midcap 150" },
  { symbol: "INDUSINDBK.NS", name: "IndusInd Bank", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "NAUKRI.NS", name: "Info Edge (India)", sector: "Consumer Services", index: "Nifty Midcap 150" },
  { symbol: "IPCALAB.NS", name: "Ipca Laboratories", sector: "Healthcare", index: "Nifty Midcap 150" },
  { symbol: "JKCEMENT.NS", name: "J.K. Cement", sector: "Construction Materials", index: "Nifty Midcap 150" },
  { symbol: "JSWENERGY.NS", name: "JSW Energy", sector: "Power", index: "Nifty Midcap 150" },
  { symbol: "JSWINFRA.NS", name: "JSW Infrastructure", sector: "Services", index: "Nifty Midcap 150" },
  { symbol: "JSL.NS", name: "Jindal Stainless", sector: "Metals & Mining", index: "Nifty Midcap 150" },
  { symbol: "JUBLFOOD.NS", name: "Jubilant Foodworks", sector: "Consumer Services", index: "Nifty Midcap 150" },
  { symbol: "KPRMILL.NS", name: "K.P.R. Mill", sector: "Textiles", index: "Nifty Midcap 150" },
  { symbol: "KEI.NS", name: "KEI Industries", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "KPITTECH.NS", name: "KPIT Technologies", sector: "Information Technology", index: "Nifty Midcap 150" },
  { symbol: "KALYANKJIL.NS", name: "Kalyan Jewellers India", sector: "Consumer Durables", index: "Nifty Midcap 150" },
  { symbol: "LTF.NS", name: "L&T Finance", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "LTTS.NS", name: "L&T Technology Services", sector: "Information Technology", index: "Nifty Midcap 150" },
  { symbol: "LGEINDIA.NS", name: "LG Electronics India", sector: "Consumer Durables", index: "Nifty Midcap 150" },
  { symbol: "LICHSGFIN.NS", name: "LIC Housing Finance", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "LAURUSLABS.NS", name: "Laurus Labs", sector: "Healthcare", index: "Nifty Midcap 150" },
  { symbol: "LENSKART.NS", name: "Lenskart Solutions", sector: "Consumer Services", index: "Nifty Midcap 150" },
  { symbol: "LICI.NS", name: "Life Insurance Corporation of India", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "LINDEINDIA.NS", name: "Linde India", sector: "Chemicals", index: "Nifty Midcap 150" },
  { symbol: "LLOYDSME.NS", name: "Lloyds Metals And Energy", sector: "Metals & Mining", index: "Nifty Midcap 150" },
  { symbol: "LUPIN.NS", name: "Lupin", sector: "Healthcare", index: "Nifty Midcap 150" },
  { symbol: "MRF.NS", name: "MRF", sector: "Automobile and Auto Components", index: "Nifty Midcap 150" },
  { symbol: "M&MFIN.NS", name: "Mahindra & Mahindra Financial Services", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "MANKIND.NS", name: "Mankind Pharma", sector: "Healthcare", index: "Nifty Midcap 150" },
  { symbol: "MARICO.NS", name: "Marico", sector: "Fast Moving Consumer Goods", index: "Nifty Midcap 150" },
  { symbol: "MFSL.NS", name: "Max Financial Services", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "MOTILALOFS.NS", name: "Motilal Oswal Financial Services", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "MPHASIS.NS", name: "MphasiS", sector: "Information Technology", index: "Nifty Midcap 150" },
  { symbol: "MCX.NS", name: "Multi Commodity Exchange of India", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "NHPC.NS", name: "NHPC", sector: "Power", index: "Nifty Midcap 150" },
  { symbol: "NLCINDIA.NS", name: "NLC India", sector: "Power", index: "Nifty Midcap 150" },
  { symbol: "NMDC.NS", name: "NMDC", sector: "Metals & Mining", index: "Nifty Midcap 150" },
  { symbol: "NTPCGREEN.NS", name: "NTPC Green Energy", sector: "Power", index: "Nifty Midcap 150" },
  { symbol: "NATIONALUM.NS", name: "National Aluminium Co.", sector: "Metals & Mining", index: "Nifty Midcap 150" },
  { symbol: "NAM-INDIA.NS", name: "Nippon Life India Asset Management", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "OBEROIRLTY.NS", name: "Oberoi Realty", sector: "Realty", index: "Nifty Midcap 150" },
  { symbol: "OIL.NS", name: "Oil India", sector: "Oil Gas & Consumable Fuels", index: "Nifty Midcap 150" },
  { symbol: "PAYTM.NS", name: "One 97 Communications", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "OFSS.NS", name: "Oracle Financial Services Software", sector: "Information Technology", index: "Nifty Midcap 150" },
  { symbol: "POLICYBZR.NS", name: "PB Fintech", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "PIIND.NS", name: "PI Industries", sector: "Chemicals", index: "Nifty Midcap 150" },
  { symbol: "PAGEIND.NS", name: "Page Industries", sector: "Textiles", index: "Nifty Midcap 150" },
  { symbol: "PATANJALI.NS", name: "Patanjali Foods", sector: "Fast Moving Consumer Goods", index: "Nifty Midcap 150" },
  { symbol: "PERSISTENT.NS", name: "Persistent Systems", sector: "Information Technology", index: "Nifty Midcap 150" },
  { symbol: "PETRONET.NS", name: "Petronet LNG", sector: "Oil Gas & Consumable Fuels", index: "Nifty Midcap 150" },
  { symbol: "PHOENIXLTD.NS", name: "Phoenix Mills", sector: "Realty", index: "Nifty Midcap 150" },
  { symbol: "POLYCAB.NS", name: "Polycab India", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "PREMIERENE.NS", name: "Premier Energies", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "PRESTIGE.NS", name: "Prestige Estates Projects", sector: "Realty", index: "Nifty Midcap 150" },
  { symbol: "RADICO.NS", name: "Radico Khaitan", sector: "Fast Moving Consumer Goods", index: "Nifty Midcap 150" },
  { symbol: "RVNL.NS", name: "Rail Vikas Nigam", sector: "Construction", index: "Nifty Midcap 150" },
  { symbol: "SBICARD.NS", name: "SBI Cards and Payment Services", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "SJVN.NS", name: "SJVN", sector: "Power", index: "Nifty Midcap 150" },
  { symbol: "SRF.NS", name: "SRF", sector: "Chemicals", index: "Nifty Midcap 150" },
  { symbol: "SCHAEFFLER.NS", name: "Schaeffler India", sector: "Automobile and Auto Components", index: "Nifty Midcap 150" },
  { symbol: "SAIL.NS", name: "Steel Authority of India", sector: "Metals & Mining", index: "Nifty Midcap 150" },
  { symbol: "SUNDARMFIN.NS", name: "Sundaram Finance", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "SUPREMEIND.NS", name: "Supreme Industries", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "SUZLON.NS", name: "Suzlon Energy", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "SWIGGY.NS", name: "Swiggy", sector: "Consumer Services", index: "Nifty Midcap 150" },
  { symbol: "TATACOMM.NS", name: "Tata Communications", sector: "Telecommunication", index: "Nifty Midcap 150" },
  { symbol: "TATAELXSI.NS", name: "Tata Elxsi", sector: "Information Technology", index: "Nifty Midcap 150" },
  { symbol: "TATAINVEST.NS", name: "Tata Investment Corporation", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "NIACL.NS", name: "The New India Assurance Company", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "THERMAX.NS", name: "Thermax", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "TORNTPOWER.NS", name: "Torrent Power", sector: "Power", index: "Nifty Midcap 150" },
  { symbol: "TIINDIA.NS", name: "Tube Investments of India", sector: "Automobile and Auto Components", index: "Nifty Midcap 150" },
  { symbol: "UNOMINDA.NS", name: "UNO Minda", sector: "Automobile and Auto Components", index: "Nifty Midcap 150" },
  { symbol: "UPL.NS", name: "UPL", sector: "Chemicals", index: "Nifty Midcap 150" },
  { symbol: "UBL.NS", name: "United Breweries", sector: "Fast Moving Consumer Goods", index: "Nifty Midcap 150" },
  { symbol: "VMM.NS", name: "Vishal Mega Mart", sector: "Consumer Services", index: "Nifty Midcap 150" },
  { symbol: "IDEA.NS", name: "Vodafone Idea", sector: "Telecommunication", index: "Nifty Midcap 150" },
  { symbol: "VOLTAS.NS", name: "Voltas", sector: "Consumer Durables", index: "Nifty Midcap 150" },
  { symbol: "WAAREEENER.NS", name: "Waaree Energies", sector: "Capital Goods", index: "Nifty Midcap 150" },
  { symbol: "YESBANK.NS", name: "Yes Bank", sector: "Financial Services", index: "Nifty Midcap 150" },
  { symbol: "ACMESOLAR.NS", name: "ACME Solar Holdings", sector: "Power", index: "Nifty Smallcap 250" },
  { symbol: "AADHARHFC.NS", name: "Aadhar Housing Finance", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "AARTIIND.NS", name: "Aarti Industries", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "AAVAS.NS", name: "Aavas Financiers", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "ACE.NS", name: "Action Construction Equipment", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "ACUTAAS.NS", name: "Acutaas Chemicals", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "ABFRL.NS", name: "Aditya Birla Fashion and Retail", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "ABLBL.NS", name: "Aditya Birla Lifestyle Brands", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "ABREL.NS", name: "Aditya Birla Real Estate", sector: "Realty", index: "Nifty Smallcap 250" },
  { symbol: "ABSLAMC.NS", name: "Aditya Birla Sun Life AMC", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "CPPLUS.NS", name: "Aditya Infotech", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "AEGISLOG.NS", name: "Aegis Logistics", sector: "Oil Gas & Consumable Fuels", index: "Nifty Smallcap 250" },
  { symbol: "AEGISVOPAK.NS", name: "Aegis Vopak Terminals", sector: "Oil Gas & Consumable Fuels", index: "Nifty Smallcap 250" },
  { symbol: "AFCONS.NS", name: "Afcons Infrastructure", sector: "Construction", index: "Nifty Smallcap 250" },
  { symbol: "AFFLE.NS", name: "Affle 3i", sector: "Information Technology", index: "Nifty Smallcap 250" },
  { symbol: "ABDL.NS", name: "Allied Blenders and Distillers", sector: "Fast Moving Consumer Goods", index: "Nifty Smallcap 250" },
  { symbol: "ARE&M.NS", name: "Amara Raja Energy & Mobility", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "AMBER.NS", name: "Amber Enterprises India", sector: "Consumer Durables", index: "Nifty Smallcap 250" },
  { symbol: "ANANDRATHI.NS", name: "Anand Rathi Wealth", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "ANANTRAJ.NS", name: "Anant Raj", sector: "Realty", index: "Nifty Smallcap 250" },
  { symbol: "ANGELONE.NS", name: "Angel One", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "ANURAS.NS", name: "Anupam Rasayan India", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "APTUS.NS", name: "Aptus Value Housing Finance India", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "ASAHIINDIA.NS", name: "Asahi India Glass", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "ASTERDM.NS", name: "Aster DM Healthcare", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "ATHERENERG.NS", name: "Ather Energy", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "ATUL.NS", name: "Atul", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "BEML.NS", name: "BEML", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "BLS.NS", name: "BLS International Services", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "BALRAMCHIN.NS", name: "Balrampur Chini Mills", sector: "Fast Moving Consumer Goods", index: "Nifty Smallcap 250" },
  { symbol: "BANDHANBNK.NS", name: "Bandhan Bank", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "BATAINDIA.NS", name: "Bata India", sector: "Consumer Durables", index: "Nifty Smallcap 250" },
  { symbol: "BAYERCROP.NS", name: "Bayer Cropscience", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "BELRISE.NS", name: "Belrise Industries", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "BIKAJI.NS", name: "Bikaji Foods International", sector: "Fast Moving Consumer Goods", index: "Nifty Smallcap 250" },
  { symbol: "BSOFT.NS", name: "Birlasoft", sector: "Information Technology", index: "Nifty Smallcap 250" },
  { symbol: "BLUEDART.NS", name: "Blue Dart Express", sector: "Services", index: "Nifty Smallcap 250" },
  { symbol: "BLUEJET.NS", name: "Blue Jet Healthcare", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "BBTC.NS", name: "Bombay Burmah Trading Corporation", sector: "Fast Moving Consumer Goods", index: "Nifty Smallcap 250" },
  { symbol: "FIRSTCRY.NS", name: "Brainbees Solutions", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "BRIGADE.NS", name: "Brigade Enterprises", sector: "Realty", index: "Nifty Smallcap 250" },
  { symbol: "MAPMYINDIA.NS", name: "C.E. Info Systems", sector: "Information Technology", index: "Nifty Smallcap 250" },
  { symbol: "CCL.NS", name: "CCL Products (I)", sector: "Fast Moving Consumer Goods", index: "Nifty Smallcap 250" },
  { symbol: "CESC.NS", name: "CESC", sector: "Power", index: "Nifty Smallcap 250" },
  { symbol: "CIEINDIA.NS", name: "CIE Automotive India", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "CANFINHOME.NS", name: "Can Fin Homes", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "CANHLIFE.NS", name: "Canara HSBC Life Insurance Company", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "CAPLIPOINT.NS", name: "Caplin Point Laboratories", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "CGCL.NS", name: "Capri Global Capital", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "CARBORUNIV.NS", name: "Carborundum Universal", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "CARTRADE.NS", name: "Cartrade Tech", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "CASTROLIND.NS", name: "Castrol India", sector: "Oil Gas & Consumable Fuels", index: "Nifty Smallcap 250" },
  { symbol: "CEATLTD.NS", name: "Ceat", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "CEMPRO.NS", name: "Cemindia Projects", sector: "Construction", index: "Nifty Smallcap 250" },
  { symbol: "CENTRALBK.NS", name: "Central Bank of India", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "CDSL.NS", name: "Central Depository Services (India)", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "CHALET.NS", name: "Chalet Hotels", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "CHAMBLFERT.NS", name: "Chambal Fertilizers & Chemicals", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "CHENNPETRO.NS", name: "Chennai Petroleum Corporation", sector: "Oil Gas & Consumable Fuels", index: "Nifty Smallcap 250" },
  { symbol: "CHOICEIN.NS", name: "Choice International", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "CHOLAHLDNG.NS", name: "Cholamandalam Financial Holdings", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "CUB.NS", name: "City Union Bank", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "CLEAN.NS", name: "Clean Science and Technology", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "COHANCE.NS", name: "Cohance Lifesciences", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "CAMS.NS", name: "Computer Age Management Services", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "CONCORDBIO.NS", name: "Concord Biotech", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "CRAFTSMAN.NS", name: "Craftsman Automation", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "CREDITACC.NS", name: "CreditAccess Grameen", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "CROMPTON.NS", name: "Crompton Greaves Consumer Electricals", sector: "Consumer Durables", index: "Nifty Smallcap 250" },
  { symbol: "CYIENT.NS", name: "Cyient", sector: "Information Technology", index: "Nifty Smallcap 250" },
  { symbol: "DCMSHRIRAM.NS", name: "DCM Shriram", sector: "Diversified", index: "Nifty Smallcap 250" },
  { symbol: "DOMS.NS", name: "DOMS Industries", sector: "Fast Moving Consumer Goods", index: "Nifty Smallcap 250" },
  { symbol: "DATAPATTNS.NS", name: "Data Patterns (India)", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "DEEPAKFERT.NS", name: "Deepak Fertilisers & Petrochemicals Corp.", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "DEEPAKNTR.NS", name: "Deepak Nitrite", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "DELHIVERY.NS", name: "Delhivery", sector: "Services", index: "Nifty Smallcap 250" },
  { symbol: "DEVYANI.NS", name: "Devyani International", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "LALPATHLAB.NS", name: "Dr. Lal Path Labs", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "EIDPARRY.NS", name: "E.I.D. Parry (India)", sector: "Fast Moving Consumer Goods", index: "Nifty Smallcap 250" },
  { symbol: "EIHOTEL.NS", name: "EIH", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "ELECON.NS", name: "Elecon Engineering Co.", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "ELGIEQUIP.NS", name: "Elgi Equipments", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "EMAMILTD.NS", name: "Emami", sector: "Fast Moving Consumer Goods", index: "Nifty Smallcap 250" },
  { symbol: "EMCURE.NS", name: "Emcure Pharmaceuticals", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "EMMVEE.NS", name: "Emmvee Photovoltaic Power", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "ENGINERSIN.NS", name: "Engineers India", sector: "Construction", index: "Nifty Smallcap 250" },
  { symbol: "ERIS.NS", name: "Eris Lifesciences", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "FACT.NS", name: "Fertilisers and Chemicals Travancore", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "FINCABLES.NS", name: "Finolex Cables", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "FSL.NS", name: "Firstsource Solutions", sector: "Services", index: "Nifty Smallcap 250" },
  { symbol: "FIVESTAR.NS", name: "Five-Star Business Finance", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "FORCEMOT.NS", name: "Force Motors", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "GABRIEL.NS", name: "Gabriel India", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "GALLANTT.NS", name: "Gallantt Ispat", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "GRSE.NS", name: "Garden Reach Shipbuilders & Engineers", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "GILLETTE.NS", name: "Gillette India", sector: "Fast Moving Consumer Goods", index: "Nifty Smallcap 250" },
  { symbol: "GLAND.NS", name: "Gland Pharma", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "GODIGIT.NS", name: "Go Digit General Insurance", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "GPIL.NS", name: "Godawari Power & Ispat", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "GRANULES.NS", name: "Granules India", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "GRAPHITE.NS", name: "Graphite India", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "GRAVITA.NS", name: "Gravita India", sector: "Metals & Mining", index: "Nifty Smallcap 250" },
  { symbol: "GESHIP.NS", name: "Great Eastern Shipping Co.", sector: "Services", index: "Nifty Smallcap 250" },
  { symbol: "GMDCLTD.NS", name: "Gujarat Mineral Development Corporation", sector: "Metals & Mining", index: "Nifty Smallcap 250" },
  { symbol: "HEG.NS", name: "H.E.G.", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "HBLENGINE.NS", name: "HBL Engineering", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "HFCL.NS", name: "HFCL", sector: "Telecommunication", index: "Nifty Smallcap 250" },
  { symbol: "HSCL.NS", name: "Himadri Speciality Chemical", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "HINDCOPPER.NS", name: "Hindustan Copper", sector: "Metals & Mining", index: "Nifty Smallcap 250" },
  { symbol: "HOMEFIRST.NS", name: "Home First Finance Company India", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "HONASA.NS", name: "Honasa Consumer", sector: "Fast Moving Consumer Goods", index: "Nifty Smallcap 250" },
  { symbol: "IDBI.NS", name: "IDBI Bank", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "IFCI.NS", name: "IFCI", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "IIFL.NS", name: "IIFL Finance", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "IRB.NS", name: "IRB Infrastructure Developers", sector: "Construction", index: "Nifty Smallcap 250" },
  { symbol: "IRCON.NS", name: "IRCON International", sector: "Construction", index: "Nifty Smallcap 250" },
  { symbol: "ITI.NS", name: "ITI", sector: "Telecommunication", index: "Nifty Smallcap 250" },
  { symbol: "INDGN.NS", name: "Indegene", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "INDIACEM.NS", name: "India Cements", sector: "Construction Materials", index: "Nifty Smallcap 250" },
  { symbol: "INDIAMART.NS", name: "Indiamart Intermesh", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "IEX.NS", name: "Indian Energy Exchange", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "IOB.NS", name: "Indian Overseas Bank", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "IGL.NS", name: "Indraprastha Gas", sector: "Oil Gas & Consumable Fuels", index: "Nifty Smallcap 250" },
  { symbol: "INOXWIND.NS", name: "Inox Wind", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "INTELLECT.NS", name: "Intellect Design Arena", sector: "Information Technology", index: "Nifty Smallcap 250" },
  { symbol: "IGIL.NS", name: "International Gemological Institute", sector: "Services", index: "Nifty Smallcap 250" },
  { symbol: "IKS.NS", name: "Inventurus Knowledge Solutions", sector: "Information Technology", index: "Nifty Smallcap 250" },
  { symbol: "JBMA.NS", name: "JBM Auto", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "JKTYRE.NS", name: "JK Tyre & Industries", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "JMFINANCIL.NS", name: "JM Financial", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "JSWCEMENT.NS", name: "JSW Cement", sector: "Construction Materials", index: "Nifty Smallcap 250" },
  { symbol: "JSWDULUX.NS", name: "JSW Dulux", sector: "Consumer Durables", index: "Nifty Smallcap 250" },
  { symbol: "JAINREC.NS", name: "Jain Resource Recycling", sector: "Metals & Mining", index: "Nifty Smallcap 250" },
  { symbol: "JPPOWER.NS", name: "Jaiprakash Power Ventures", sector: "Power", index: "Nifty Smallcap 250" },
  { symbol: "J&KBANK.NS", name: "Jammu & Kashmir Bank", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "JINDALSAW.NS", name: "Jindal Saw", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "JUBLINGREA.NS", name: "Jubilant Ingrevia", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "JUBLPHARMA.NS", name: "Jubilant Pharmova", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "JWL.NS", name: "Jupiter Wagons", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "JYOTICNC.NS", name: "Jyoti CNC Automation", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "KAJARIACER.NS", name: "Kajaria Ceramics", sector: "Consumer Durables", index: "Nifty Smallcap 250" },
  { symbol: "KPIL.NS", name: "Kalpataru Projects International", sector: "Construction", index: "Nifty Smallcap 250" },
  { symbol: "KARURVYSYA.NS", name: "Karur Vysya Bank", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "KAYNES.NS", name: "Kaynes Technology India", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "KEC.NS", name: "Kec International", sector: "Construction", index: "Nifty Smallcap 250" },
  { symbol: "KFINTECH.NS", name: "Kfin Technologies", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "KIRLOSENG.NS", name: "Kirloskar Oil Eng", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "KIMS.NS", name: "Krishna Institute of Medical Sciences", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "LTFOODS.NS", name: "LT Foods", sector: "Fast Moving Consumer Goods", index: "Nifty Smallcap 250" },
  { symbol: "LATENTVIEW.NS", name: "Latent View Analytics", sector: "Information Technology", index: "Nifty Smallcap 250" },
  { symbol: "THELEELA.NS", name: "Leela Palaces Hotels & Resorts", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "LEMONTREE.NS", name: "Lemon Tree Hotels", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "MMTC.NS", name: "MMTC", sector: "Services", index: "Nifty Smallcap 250" },
  { symbol: "MGL.NS", name: "Mahanagar Gas", sector: "Oil Gas & Consumable Fuels", index: "Nifty Smallcap 250" },
  { symbol: "MANAPPURAM.NS", name: "Manappuram Finance", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "MRPL.NS", name: "Mangalore Refinery & Petrochemicals", sector: "Oil Gas & Consumable Fuels", index: "Nifty Smallcap 250" },
  { symbol: "MEESHO.NS", name: "Meesho", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "MINDACORP.NS", name: "Minda Corporation", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "MSUMI.NS", name: "Motherson Sumi Wiring India", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "NATCOPHARM.NS", name: "NATCO Pharma", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "NBCC.NS", name: "NBCC (India)", sector: "Construction", index: "Nifty Smallcap 250" },
  { symbol: "NCC.NS", name: "NCC", sector: "Construction", index: "Nifty Smallcap 250" },
  { symbol: "NSLNISP.NS", name: "NMDC Steel", sector: "Metals & Mining", index: "Nifty Smallcap 250" },
  { symbol: "NH.NS", name: "Narayana Hrudayalaya", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "NAVA.NS", name: "Nava", sector: "Power", index: "Nifty Smallcap 250" },
  { symbol: "NAVINFLUOR.NS", name: "Navin Fluorine International", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "NETWEB.NS", name: "Netweb Technologies India", sector: "Information Technology", index: "Nifty Smallcap 250" },
  { symbol: "NEULANDLAB.NS", name: "Neuland Laboratories", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "NEWGEN.NS", name: "Newgen Software Technologies", sector: "Information Technology", index: "Nifty Smallcap 250" },
  { symbol: "NIVABUPA.NS", name: "Niva Bupa Health Insurance Company", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "NUVAMA.NS", name: "Nuvama Wealth Management", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "NUVOCO.NS", name: "Nuvoco Vistas Corporation", sector: "Construction Materials", index: "Nifty Smallcap 250" },
  { symbol: "OLAELEC.NS", name: "Ola Electric Mobility", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "OLECTRA.NS", name: "Olectra Greentech", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "ONESOURCE.NS", name: "Onesource Specialty Pharma", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "PCBL.NS", name: "PCBL Chemical", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "PGEL.NS", name: "PG Electroplast", sector: "Consumer Durables", index: "Nifty Smallcap 250" },
  { symbol: "PNBHOUSING.NS", name: "PNB Housing Finance", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "PTCIL.NS", name: "PTC Industries", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "PVRINOX.NS", name: "PVR INOX", sector: "Media Entertainment & Publication", index: "Nifty Smallcap 250" },
  { symbol: "PARADEEP.NS", name: "Paradeep Phosphates", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "PFIZER.NS", name: "Pfizer", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "PWL.NS", name: "Physicswallah", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "PINELABS.NS", name: "Pine Labs", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "PIRAMALFIN.NS", name: "Piramal Finance", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "PPLPHARMA.NS", name: "Piramal Pharma", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "POLYMED.NS", name: "Poly Medicure", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "POONAWALLA.NS", name: "Poonawalla Fincorp", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "PFOCUS.NS", name: "Prime Focus", sector: "Media Entertainment & Publication", index: "Nifty Smallcap 250" },
  { symbol: "RRKABEL.NS", name: "R R Kabel", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "RBLBANK.NS", name: "RBL Bank", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "RHIM.NS", name: "RHI MAGNESITA INDIA", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "RITES.NS", name: "RITES", sector: "Construction", index: "Nifty Smallcap 250" },
  { symbol: "RAILTEL.NS", name: "Railtel Corporation Of India", sector: "Telecommunication", index: "Nifty Smallcap 250" },
  { symbol: "RAINBOW.NS", name: "Rainbow Childrens Medicare", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "RKFORGE.NS", name: "Ramkrishna Forgings", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "REDINGTON.NS", name: "Redington", sector: "Services", index: "Nifty Smallcap 250" },
  { symbol: "RPOWER.NS", name: "Reliance Power", sector: "Power", index: "Nifty Smallcap 250" },
  { symbol: "SBFC.NS", name: "SBFC Finance", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "SAGILITY.NS", name: "Sagility", sector: "Information Technology", index: "Nifty Smallcap 250" },
  { symbol: "SAILIFE.NS", name: "Sai Life Sciences", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "SAMMAANCAP.NS", name: "Sammaan Capital", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "SAPPHIRE.NS", name: "Sapphire Foods India", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "SARDAEN.NS", name: "Sarda Energy and Minerals", sector: "Metals & Mining", index: "Nifty Smallcap 250" },
  { symbol: "SAREGAMA.NS", name: "Saregama India", sector: "Media Entertainment & Publication", index: "Nifty Smallcap 250" },
  { symbol: "SCHNEIDER.NS", name: "Schneider Electric Infrastructure", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "SCI.NS", name: "Shipping Corporation of India", sector: "Services", index: "Nifty Smallcap 250" },
  { symbol: "SHYAMMETL.NS", name: "Shyam Metalics and Energy", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "SIGNATURE.NS", name: "Signatureglobal (India)", sector: "Realty", index: "Nifty Smallcap 250" },
  { symbol: "SOBHA.NS", name: "Sobha", sector: "Realty", index: "Nifty Smallcap 250" },
  { symbol: "SONACOMS.NS", name: "Sona BLW Precision Forgings", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "SONATSOFTW.NS", name: "Sonata Software", sector: "Information Technology", index: "Nifty Smallcap 250" },
  { symbol: "STARHEALTH.NS", name: "Star Health and Allied Insurance Company", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "SUMICHEM.NS", name: "Sumitomo Chemical India", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "SUNTV.NS", name: "Sun TV Network", sector: "Media Entertainment & Publication", index: "Nifty Smallcap 250" },
  { symbol: "SPLPETRO.NS", name: "Supreme Petrochem", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "SWANCORP.NS", name: "Swan Corp", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "SYNGENE.NS", name: "Syngene International", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "SYRMA.NS", name: "Syrma SGS Technology", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "TBOTEK.NS", name: "TBO Tek", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "TATACHEM.NS", name: "Tata Chemicals", sector: "Chemicals", index: "Nifty Smallcap 250" },
  { symbol: "TATATECH.NS", name: "Tata Technologies", sector: "Information Technology", index: "Nifty Smallcap 250" },
  { symbol: "TTML.NS", name: "Tata Teleservices (Maharashtra)", sector: "Telecommunication", index: "Nifty Smallcap 250" },
  { symbol: "TECHNOE.NS", name: "Techno Electric & Engineering Company", sector: "Construction", index: "Nifty Smallcap 250" },
  { symbol: "TEGA.NS", name: "Tega Industries", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "TEJASNET.NS", name: "Tejas Networks", sector: "Telecommunication", index: "Nifty Smallcap 250" },
  { symbol: "TENNIND.NS", name: "Tenneco Clean Air India", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "RAMCOCEM.NS", name: "The Ramco Cements", sector: "Construction Materials", index: "Nifty Smallcap 250" },
  { symbol: "TIMKEN.NS", name: "Timken India", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "TITAGARH.NS", name: "Titagarh Rail Systems", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "TARIL.NS", name: "Transformers And Rectifiers (India)", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "TRAVELFOOD.NS", name: "Travel Food Services", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "TRIDENT.NS", name: "Trident", sector: "Textiles", index: "Nifty Smallcap 250" },
  { symbol: "TRITURBINE.NS", name: "Triveni Turbine", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "UCOBANK.NS", name: "UCO Bank", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "UTIAMC.NS", name: "UTI Asset Management Company", sector: "Financial Services", index: "Nifty Smallcap 250" },
  { symbol: "URBANCO.NS", name: "Urban Company", sector: "Consumer Services", index: "Nifty Smallcap 250" },
  { symbol: "USHAMART.NS", name: "Usha Martin", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "VTL.NS", name: "Vardhman Textiles", sector: "Textiles", index: "Nifty Smallcap 250" },
  { symbol: "VIJAYA.NS", name: "Vijaya Diagnostic Centre", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "WELCORP.NS", name: "Welspun Corp", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "WELSPUNLIV.NS", name: "Welspun Living", sector: "Textiles", index: "Nifty Smallcap 250" },
  { symbol: "WHIRLPOOL.NS", name: "Whirlpool of India", sector: "Consumer Durables", index: "Nifty Smallcap 250" },
  { symbol: "WOCKPHARMA.NS", name: "Wockhardt", sector: "Healthcare", index: "Nifty Smallcap 250" },
  { symbol: "ZFCVINDIA.NS", name: "ZF Commercial Vehicle Control Systems India", sector: "Automobile and Auto Components", index: "Nifty Smallcap 250" },
  { symbol: "ZEEL.NS", name: "Zee Entertainment Enterprises", sector: "Media Entertainment & Publication", index: "Nifty Smallcap 250" },
  { symbol: "ZENTEC.NS", name: "Zen Technologies", sector: "Capital Goods", index: "Nifty Smallcap 250" },
  { symbol: "ZENSARTECH.NS", name: "Zensar Technolgies", sector: "Information Technology", index: "Nifty Smallcap 250" },
  { symbol: "ZYDUSWELL.NS", name: "Zydus Wellness", sector: "Fast Moving Consumer Goods", index: "Nifty Smallcap 250" },
  { symbol: "ECLERX.NS", name: "eClerx Services", sector: "Services", index: "Nifty Smallcap 250" },
  { symbol: "ASKAUTOLTD.NS", name: "ASK Automotive", sector: "Automobile and Auto Components", index: "Nifty Microcap 250" },
  { symbol: "AXISCADES.NS", name: "AXISCADES Technologies", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "AARTIDRUGS.NS", name: "Aarti Drugs", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "AARTIPHARM.NS", name: "Aarti Pharmalabs", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "AVL.NS", name: "Aditya Vision", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "ADVENZYMES.NS", name: "Advanced Enzyme Tech", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "AEQUS.NS", name: "Aequs", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "AETHER.NS", name: "Aether Industries", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "AHLUCONT.NS", name: "Ahluwalia Contracts (India)", sector: "Construction", index: "Nifty Microcap 250" },
  { symbol: "AKUMS.NS", name: "Akums Drugs and Pharmaceuticals", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "APLLTD.NS", name: "Alembic Pharmaceuticals", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "ALIVUS.NS", name: "Alivus Life Sciences", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "ALKYLAMINE.NS", name: "Alkyl Amines Chemicals", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "AGL.NS", name: "Allcargo Global", sector: "Services", index: "Nifty Microcap 250" },
  { symbol: "ALOKINDS.NS", name: "Alok Industries", sector: "Textiles", index: "Nifty Microcap 250" },
  { symbol: "APOLLO.NS", name: "Apollo Micro Systems", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "ACI.NS", name: "Archean Chemical Industries", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "ARVINDFASN.NS", name: "Arvind Fashions", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "ARVIND.NS", name: "Arvind", sector: "Textiles", index: "Nifty Microcap 250" },
  { symbol: "ASHAPURMIN.NS", name: "Ashapura Minechem", sector: "Metals & Mining", index: "Nifty Microcap 250" },
  { symbol: "ASHOKA.NS", name: "Ashoka Buildcon", sector: "Construction", index: "Nifty Microcap 250" },
  { symbol: "ASTRAMICRO.NS", name: "Astra Microwave Products", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "ATLANTAELE.NS", name: "Atlanta Electricals", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "AURIONPRO.NS", name: "Aurionpro Solution", sector: "Information Technology", index: "Nifty Microcap 250" },
  { symbol: "AVALON.NS", name: "Avalon Technologies", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "AVANTIFEED.NS", name: "Avanti Feeds", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "CCAVENUE.NS", name: "AvenuesAI", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "AWFIS.NS", name: "Awfis Space Solutions", sector: "Services", index: "Nifty Microcap 250" },
  { symbol: "AZAD.NS", name: "Azad Engineering", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "BAJAJELEC.NS", name: "Bajaj Electricals", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "BALAMINES.NS", name: "Balaji Amines", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "BALUFORGE.NS", name: "Balu Forge Industries", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "BANCOINDIA.NS", name: "Banco Products (India)", sector: "Automobile and Auto Components", index: "Nifty Microcap 250" },
  { symbol: "BIRLACORPN.NS", name: "Birla Corporation", sector: "Construction Materials", index: "Nifty Microcap 250" },
  { symbol: "BBOX.NS", name: "Black Box", sector: "Information Technology", index: "Nifty Microcap 250" },
  { symbol: "BLACKBUCK.NS", name: "Blackbuck", sector: "Services", index: "Nifty Microcap 250" },
  { symbol: "BLUESTONE.NS", name: "BlueStone Jewellery and Lifestyle", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "BORORENEW.NS", name: "Borosil Renewables", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "CMSINFO.NS", name: "CMS Info Systems", sector: "Services", index: "Nifty Microcap 250" },
  { symbol: "CORONA.NS", name: "CORONA Remedies", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "CSBBANK.NS", name: "CSB Bank", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "CAMPUS.NS", name: "Campus Activewear", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "CRAMC.NS", name: "Canara Robeco Asset Management Company", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "CAPILLARY.NS", name: "Capillary Technologies India", sector: "Information Technology", index: "Nifty Microcap 250" },
  { symbol: "CELLO.NS", name: "Cello World", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "CENTURYPLY.NS", name: "Century Plyboards (India)", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "CERA.NS", name: "Cera Sanitaryware", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "CRIZAC.NS", name: "Crizac", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "CUPID.NS", name: "Cupid", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "DCBBANK.NS", name: "DCB Bank", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "DATAMATICS.NS", name: "Datamatics Global Services", sector: "Information Technology", index: "Nifty Microcap 250" },
  { symbol: "DIACABS.NS", name: "Diamond Power Infrastructure", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "DBL.NS", name: "Dilip Buildcon", sector: "Construction", index: "Nifty Microcap 250" },
  { symbol: "AGARWALEYE.NS", name: "Dr. Agarwal's Health Care", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "DYNAMATECH.NS", name: "Dynamatic Technologies", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "EPL.NS", name: "EPL", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "EDELWEISS.NS", name: "Edelweiss Financial Services", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "EMIL.NS", name: "Electronics Mart India", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "ELECTCAST.NS", name: "Electrosteel Castings", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "ELLEN.NS", name: "Ellenbarrie Industrial Gases", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "EMBDL.NS", name: "Embassy Developments", sector: "Realty", index: "Nifty Microcap 250" },
  { symbol: "ENTERO.NS", name: "Entero Healthcare Solutions", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "EIEL.NS", name: "Enviro Infra Engineers", sector: "Utilities", index: "Nifty Microcap 250" },
  { symbol: "EQUITASBNK.NS", name: "Equitas Small Finance Bank", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "ETHOSLTD.NS", name: "Ethos", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "EUREKAFORB.NS", name: "Eureka Forbes", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "FEDFINA.NS", name: "Fedbank Financial Services", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "FIEMIND.NS", name: "Fiem Industries", sector: "Automobile and Auto Components", index: "Nifty Microcap 250" },
  { symbol: "FINPIPE.NS", name: "Finolex Industries", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "UTLSOLAR.NS", name: "Fujiyama Power Systems", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "GHCL.NS", name: "GHCL", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "GMMPFAUDLR.NS", name: "GMM Pfaudler", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "GMRP&UI.NS", name: "GMR Power and Urban Infra", sector: "Power", index: "Nifty Microcap 250" },
  { symbol: "GRWRHITECH.NS", name: "Garware Hi-Tech Films", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "GODREJAGRO.NS", name: "Godrej Agrovet", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "GOKEX.NS", name: "Gokaldas Exports", sector: "Textiles", index: "Nifty Microcap 250" },
  { symbol: "GOKULAGRO.NS", name: "Gokul Agro Resources", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "GREAVESCOT.NS", name: "Greaves Cotton", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "GRINDWELL.NS", name: "Grindwell Norton", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "GAEL.NS", name: "Gujarat Ambuja Exports", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "GNFC.NS", name: "Gujarat Narmada Valley Fertilizers and Chemicals", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "GPPL.NS", name: "Gujarat Pipavav Port", sector: "Services", index: "Nifty Microcap 250" },
  { symbol: "GSFC.NS", name: "Gujarat State Fertilizers & Chemicals", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "HGINFRA.NS", name: "H.G. Infra Engineering", sector: "Construction", index: "Nifty Microcap 250" },
  { symbol: "HAPPSTMNDS.NS", name: "Happiest Minds Technologies", sector: "Information Technology", index: "Nifty Microcap 250" },
  { symbol: "HCG.NS", name: "Healthcare Global Enterprises", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "HEMIPROP.NS", name: "Hemisphere Properties India", sector: "Services", index: "Nifty Microcap 250" },
  { symbol: "HERITGFOOD.NS", name: "Heritage Foods", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "HCC.NS", name: "Hindustan Construction Co.", sector: "Construction", index: "Nifty Microcap 250" },
  { symbol: "IFBIND.NS", name: "IFB Industries", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "IIFLCAPS.NS", name: "IIFL Capital Services", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "INOXINDIA.NS", name: "INOX India", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "INDIAGLYCO.NS", name: "India Glycols", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "INDIASHLTR.NS", name: "India Shelter Finance Corporation", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "IMFA.NS", name: "Indian Metals & Ferro Alloys", sector: "Metals & Mining", index: "Nifty Microcap 250" },
  { symbol: "INDIGOPNTS.NS", name: "Indigo Paints", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "ICIL.NS", name: "Indo Count Industries", sector: "Textiles", index: "Nifty Microcap 250" },
  { symbol: "INOXGREEN.NS", name: "Inox Green Energy Services", sector: "Services", index: "Nifty Microcap 250" },
  { symbol: "IONEXCHANG.NS", name: "Ion Exchange (India)", sector: "Utilities", index: "Nifty Microcap 250" },
  { symbol: "JKLAKSHMI.NS", name: "JK Lakshmi Cement", sector: "Construction Materials", index: "Nifty Microcap 250" },
  { symbol: "JKPAPER.NS", name: "JK Paper", sector: "Forest Materials", index: "Nifty Microcap 250" },
  { symbol: "JAIBALAJI.NS", name: "Jai Balaji Industries", sector: "Metals & Mining", index: "Nifty Microcap 250" },
  { symbol: "JAMNAAUTO.NS", name: "Jamna Auto Industries", sector: "Automobile and Auto Components", index: "Nifty Microcap 250" },
  { symbol: "JSFB.NS", name: "Jana Small Finance Bank", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "JAYNECOIND.NS", name: "Jayaswal Neco Industries", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "JSLL.NS", name: "Jeena Sikho Lifecare", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "JLHL.NS", name: "Jupiter Life Line Hospitals", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "JUSTDIAL.NS", name: "Justdial", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "JYOTHYLAB.NS", name: "Jyothy Labs", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "KNRCON.NS", name: "KNR Constructions", sector: "Construction", index: "Nifty Microcap 250" },
  { symbol: "KPIGREEN.NS", name: "KPI Green Energy", sector: "Power", index: "Nifty Microcap 250" },
  { symbol: "KRBL.NS", name: "KRBL", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "KRN.NS", name: "KRN Heat Exchanger and Refrigeration", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "KSB.NS", name: "KSB", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "KANSAINER.NS", name: "Kansai Nerolac Paints", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "KTKBANK.NS", name: "Karnataka Bank", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "KSCL.NS", name: "Kaveri Seed Company", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "KIRLOSBROS.NS", name: "Kirloskar Brothers", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "KIRLPNU.NS", name: "Kirloskar Pneumatic Company", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "KITEX.NS", name: "Kitex Garments", sector: "Textiles", index: "Nifty Microcap 250" },
  { symbol: "LXCHEM.NS", name: "Laxmi Organic Industries", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "IXIGO.NS", name: "Le Travenues Technology", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "LLOYDSENGG.NS", name: "Lloyds Engineering Works", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "LLOYDSENT.NS", name: "Lloyds Enterprises", sector: "Metals & Mining", index: "Nifty Microcap 250" },
  { symbol: "LUMAXTECH.NS", name: "Lumax Auto Technologies", sector: "Automobile and Auto Components", index: "Nifty Microcap 250" },
  { symbol: "MOIL.NS", name: "MOIL", sector: "Metals & Mining", index: "Nifty Microcap 250" },
  { symbol: "MSTCLTD.NS", name: "MSTC", sector: "Services", index: "Nifty Microcap 250" },
  { symbol: "MTARTECH.NS", name: "MTAR Technologies", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "MAHSCOOTER.NS", name: "Maharashtra Scooters", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "MAHSEAMLES.NS", name: "Maharashtra Seamless", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "MANORAMA.NS", name: "Manorama Industries", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "MARKSANS.NS", name: "Marksans Pharma", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "MASTEK.NS", name: "Mastek", sector: "Information Technology", index: "Nifty Microcap 250" },
  { symbol: "MEDPLUS.NS", name: "Medplus Health Services", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "METROPOLIS.NS", name: "Metropolis Healthcare", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "MIDHANI.NS", name: "Mishra Dhatu Nigam", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "BECTORFOOD.NS", name: "Mrs. Bectors Food Specialities", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "NEOGEN.NS", name: "NEOGEN CHEMICALS", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "NESCO.NS", name: "NESCO", sector: "Services", index: "Nifty Microcap 250" },
  { symbol: "NFL.NS", name: "National Fertilizers", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "NAZARA.NS", name: "Nazara Technologies", sector: "Media Entertainment & Publication", index: "Nifty Microcap 250" },
  { symbol: "NETWORK18.NS", name: "Network18 Media & Investments", sector: "Media Entertainment & Publication", index: "Nifty Microcap 250" },
  { symbol: "OPTIEMUS.NS", name: "Optiemus Infracom", sector: "Telecommunication", index: "Nifty Microcap 250" },
  { symbol: "ORIENTCEM.NS", name: "Orient Cement", sector: "Construction Materials", index: "Nifty Microcap 250" },
  { symbol: "ORKLAINDIA.NS", name: "Orkla India", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "OSWALPUMPS.NS", name: "Oswal Pumps", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "PNGJL.NS", name: "P N Gadgil Jewellers", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "PCJEWELLER.NS", name: "PC Jeweller", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "PNCINFRA.NS", name: "PNC Infratech", sector: "Construction", index: "Nifty Microcap 250" },
  { symbol: "PTC.NS", name: "PTC India", sector: "Power", index: "Nifty Microcap 250" },
  { symbol: "PARAS.NS", name: "Paras Defence and Space Technologies", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "PARKHOSPS.NS", name: "Park Medi World", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "PGIL.NS", name: "Pearl Global Industries", sector: "Textiles", index: "Nifty Microcap 250" },
  { symbol: "PICCADIL.NS", name: "Piccadily Agro Industries", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "POWERMECH.NS", name: "Power Mech Projects", sector: "Construction", index: "Nifty Microcap 250" },
  { symbol: "PRAJIND.NS", name: "Praj Industries", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "PRICOLLTD.NS", name: "Pricol", sector: "Automobile and Auto Components", index: "Nifty Microcap 250" },
  { symbol: "PRSMJOHNSN.NS", name: "Prism Johnson", sector: "Construction Materials", index: "Nifty Microcap 250" },
  { symbol: "PRIVISCL.NS", name: "Privi Speciality Chemicals", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "PRUDENT.NS", name: "Prudent Corporate Advisory Services", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "PURVA.NS", name: "Puravankara", sector: "Realty", index: "Nifty Microcap 250" },
  { symbol: "QPOWER.NS", name: "Quality Power Electrical Equipments", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "QUESS.NS", name: "Quess Corp", sector: "Services", index: "Nifty Microcap 250" },
  { symbol: "RAIN.NS", name: "Rain Industries", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "RALLIS.NS", name: "Rallis India", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "RCF.NS", name: "Rashtriya Chemicals & Fertilizers", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "RATEGAIN.NS", name: "Rategain Travel Technologies", sector: "Information Technology", index: "Nifty Microcap 250" },
  { symbol: "RATNAMANI.NS", name: "Ratnamani Metals & Tubes", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "RTNINDIA.NS", name: "RattanIndia Enterprises", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "RTNPOWER.NS", name: "RattanIndia Power", sector: "Power", index: "Nifty Microcap 250" },
  { symbol: "RAYMONDLSL.NS", name: "Raymond Lifestyle", sector: "Textiles", index: "Nifty Microcap 250" },
  { symbol: "REDTAPE.NS", name: "Redtape", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "REFEX.NS", name: "Refex Industries", sector: "Utilities", index: "Nifty Microcap 250" },
  { symbol: "RELAXO.NS", name: "Relaxo Footwears", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "RELIGARE.NS", name: "Religare Enterprises", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "RBA.NS", name: "Restaurant Brands Asia", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "ROUTE.NS", name: "Route Mobile", sector: "Telecommunication", index: "Nifty Microcap 250" },
  { symbol: "RUBICON.NS", name: "Rubicon Research", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "SKFINDUS.NS", name: "SKF India (Industrial)", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "SKFINDIA.NS", name: "SKF India", sector: "Automobile and Auto Components", index: "Nifty Microcap 250" },
  { symbol: "SKYGOLD.NS", name: "SKY GOLD AND DIAMONDS", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "SMLMAH.NS", name: "SML Mahindra", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "SHRIPISTON.NS", name: "SPR Auto Technologies", sector: "Automobile and Auto Components", index: "Nifty Microcap 250" },
  { symbol: "SAATVIKGL.NS", name: "Saatvik Green Energy", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "SAFARI.NS", name: "Safari Industries (India)", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "SAMHI.NS", name: "Samhi Hotels", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "SANDUMA.NS", name: "Sandur Manganese & Iron Ores", sector: "Metals & Mining", index: "Nifty Microcap 250" },
  { symbol: "SANOFICONR.NS", name: "Sanofi Consumer Healthcare India", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "SANSERA.NS", name: "Sansera Engineering", sector: "Automobile and Auto Components", index: "Nifty Microcap 250" },
  { symbol: "SENCO.NS", name: "Senco Gold", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "STYL.NS", name: "Seshaasai Technologies", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "SHAILY.NS", name: "Shaily Engineering Plastics", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "SHAKTIPUMP.NS", name: "Shakti Pumps (India)", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "SHARDACROP.NS", name: "Sharda Cropchem", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "SHAREINDIA.NS", name: "Share India Securities", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "SFL.NS", name: "Sheela Foam", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "SHILPAMED.NS", name: "Shilpa Medicare", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "RENUKA.NS", name: "Shree Renuka Sugars", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "SKIPPER.NS", name: "Skipper", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "SMARTWORKS.NS", name: "Smartworks Coworking Spaces", sector: "Services", index: "Nifty Microcap 250" },
  { symbol: "SOUTHBANK.NS", name: "South Indian Bank", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "LOTUSDEV.NS", name: "Sri Lotus Developers and Realty", sector: "Realty", index: "Nifty Microcap 250" },
  { symbol: "STARCEMENT.NS", name: "Star Cement", sector: "Construction Materials", index: "Nifty Microcap 250" },
  { symbol: "SWSOLAR.NS", name: "Sterling and Wilson Renewable Energy", sector: "Construction", index: "Nifty Microcap 250" },
  { symbol: "STLTECH.NS", name: "Sterlite Technologies", sector: "Telecommunication", index: "Nifty Microcap 250" },
  { symbol: "STAR.NS", name: "Strides Pharma Science", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "STYRENIX.NS", name: "Styrenix Performance Materials", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "SUBROS.NS", name: "Subros", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "SUDARSCHEM.NS", name: "Sudarshan Chemical Industries", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "SUDEEPPHRM.NS", name: "Sudeep Pharma", sector: "Chemicals", index: "Nifty Microcap 250" },
  { symbol: "SPARC.NS", name: "Sun Pharma Advanced Research Company", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "SUNTECK.NS", name: "Sunteck Realty", sector: "Realty", index: "Nifty Microcap 250" },
  { symbol: "SUPRIYA.NS", name: "Supriya Lifescience", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "SURYAROSNI.NS", name: "Surya Roshni", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "TARC.NS", name: "TARC", sector: "Realty", index: "Nifty Microcap 250" },
  { symbol: "TDPOWERSYS.NS", name: "TD Power Systems", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "TSFINV.NS", name: "TSF Investments", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "TVSSCS.NS", name: "TVS Supply Chain Solutions", sector: "Services", index: "Nifty Microcap 250" },
  { symbol: "TMB.NS", name: "Tamilnad Mercantile Bank", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "TANLA.NS", name: "Tanla Platforms", sector: "Information Technology", index: "Nifty Microcap 250" },
  { symbol: "TEXRAIL.NS", name: "Texmaco Rail & Eng.", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "THANGAMAYL.NS", name: "Thangamayil Jewellery", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "ANUP.NS", name: "The Anup Engineering", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "THOMASCOOK.NS", name: "Thomas Cook (India)", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "THYROCARE.NS", name: "Thyrocare Technologies", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "TI.NS", name: "Tilaknagar Industries", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "TIMETECHNO.NS", name: "Time Technoplast", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "TIPSMUSIC.NS", name: "Tips Music", sector: "Media Entertainment & Publication", index: "Nifty Microcap 250" },
  { symbol: "TRANSRAILL.NS", name: "Transrail Lighting", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "TRIVENI.NS", name: "Triveni Engineering & Industries", sector: "Fast Moving Consumer Goods", index: "Nifty Microcap 250" },
  { symbol: "UJJIVANSFB.NS", name: "Ujjivan Small Finance Bank", sector: "Financial Services", index: "Nifty Microcap 250" },
  { symbol: "VGUARD.NS", name: "V-Guard Industries", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "VMART.NS", name: "V-Mart Retail", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "VIPIND.NS", name: "V.I.P. Industries", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "V2RETAIL.NS", name: "V2 Retail", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "WABAG.NS", name: "Va Tech Wabag", sector: "Utilities", index: "Nifty Microcap 250" },
  { symbol: "VAIBHAVGBL.NS", name: "Vaibhav Global", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "DBREALTY.NS", name: "Valor Estate", sector: "Realty", index: "Nifty Microcap 250" },
  { symbol: "VARROC.NS", name: "Varroc Engineering", sector: "Automobile and Auto Components", index: "Nifty Microcap 250" },
  { symbol: "MANYAVAR.NS", name: "Vedant Fashions", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "VIKRAMSOLR.NS", name: "Vikram Solar", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "VIYASH.NS", name: "Viyash Scientific", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "VOLTAMP.NS", name: "Voltamp Transformers", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "WAAREERTL.NS", name: "Waaree Renewable Technologies", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "WAKEFIT.NS", name: "Wakefit Innovations", sector: "Consumer Durables", index: "Nifty Microcap 250" },
  { symbol: "WEWORK.NS", name: "WeWork India Management", sector: "Services", index: "Nifty Microcap 250" },
  { symbol: "WEBELSOLAR.NS", name: "Websol Energy System", sector: "Capital Goods", index: "Nifty Microcap 250" },
  { symbol: "WELENT.NS", name: "Welspun Enterprises", sector: "Construction", index: "Nifty Microcap 250" },
  { symbol: "WESTLIFE.NS", name: "Westlife Foodworld", sector: "Consumer Services", index: "Nifty Microcap 250" },
  { symbol: "YATHARTH.NS", name: "Yatharth Hospital & Trauma Care Services", sector: "Healthcare", index: "Nifty Microcap 250" },
  { symbol: "ZAGGLE.NS", name: "Zaggle Prepaid Ocean Services", sector: "Information Technology", index: "Nifty Microcap 250" },
];

export const bySymbol = new Map(UNIVERSE.map((s) => [s.symbol, s]));

export function symbolsForIndex(index: IndexName): string[] {
  return UNIVERSE.filter((s) => s.index === index).map((s) => s.symbol);
}
